### ISSUE TITLE
Перейти на использование yarn

### ISSUE THREAD

**Issue by sigorilla** [banditi/chat#4]
Как стало известно, npm может устанавливать разные версии пакетов, даже если присутствует `npm-shrinkwrap.json`. В прошлом году Facebook написали утилиту над npm, которая быстрее, сохраняет версии и там есть эмодзи.

**Задача**

- Перейти на использование [yarn](https://yarnpkg.com/)
- Добавить [`.yarnrc`](https://yarnpkg.com/en/docs/yarnrc) файл, чтобы записывались точные версии в `package.json`.

> The config command may also be used to set these options.

Для этого надо добавить `save-prefix false`

[Почитать](https://habrahabr.ru/post/312458/)

**Comment by Nipel-Crumple** [comment]
На `.yarnrc` кладем сразу же, нам не особо нужна возможность разрабатываться оффлайн

**Comment by sigorilla** [comment]
npm@5 лечит все проблемы. Закрываю
