### ISSUE TITLE
vue.js

### ISSUE THREAD

**Issue by sigorilla** [banditi/chat#5]
Давайте попробуем на клиенте [vue.js](https://ru.vuejs.org/v2/guide/index.html). Почитайте про неё.

@Nipel-Crumple Возьмешь на себя? Оформи самую простую страничку, которая напишет приветствие.

При первичной настройке надо настроить [webpack](https://webpack.js.org/) для `.vue` файлов. В первой итерации используем [однофайловые компоненты ](https://ru.vuejs.org/v2/guide/single-file-components.html), как простой вариант. После можно будет разбивать их, если захотим.

На счет использования стилей никаких ограничений думаю нет, какой начнем первым использовать, такой и оставим. Из вариантов: `SASS`, `SCSS`, `Stylus`. По поводу именования классов разберемся отдельно.

@banditi/codebusters Предложения, пожелания?

**Comment by sigorilla** [comment]
Ещё [чтиво](https://geektimes.ru/company/banderolka/blog/284094/) по поводу vue.js в сравнении с другими фреймворками.

**Comment by sigorilla** [comment]
@Nipel-Crumple возьмешь? Или я возьму?

**Comment by Nipel-Crumple** [comment]
@sigorilla возьму, завтра постараюсь посмотреть

**Comment by sigorilla** [comment]
Заберу на себя
